### ISSUE TITLE
not work for cases

### ISSUE THREAD

**Issue by honkiko** [imdario/medeina#3]
for example:
It's impossible to have below 2 patterns:
-  "/hello/:param1/:param2/world"
-  "/hello/:param2/world"

Such pattern is common and taken by "docker registry API"

**Comment by darccio** [comment]
Sorry for not answering before. I'm checking the Docker's API HTTP handlers and I don't find any suitable example: https://github.com/docker/docker/blob/master/api/server/server.go

If you can point me a specific example, I'll be happy to fix it. I already created a new test (I'll push it later) to work this out. Thanks!

**Comment by honkiko** [comment]
You could just try this example:
- "/hello/:param1/:param2/world"
- "/hello/:param2/world"

**Comment by darccio** [comment]
Ok, I will check it.

**Comment by darccio** [comment]
I'm archiving this repository, as long as I no longer maintain it.
